config/routes.rb
Spree::Core::Engine.routes.draw do
  namespace :admin do
    resources :store_credit_categories
    resources :users, only: [] do
      resources :store_credits

      resources :gift_cards, only: [] do
        collection do
          get :lookup
          post :redeem
        end
      end

      collection do
        resources :gift_cards, only: [:index, :show]
      end
    end
    resources :orders, only: [] do
      resources :gift_cards, only: [:edit, :update] do
        member do
          put :send_email
          put :deactivate
        end
      end
    end
  end

  namespace :api, defaults: { format: 'json' } do
    resources :store_credit_events, only: [] do
      collection do
        get :mine
      end
    end

    resources :gift_cards, only: [] do
      collection do
        post :redeem
      end
    end
  end

  post '/checkout/redeem', to: 'checkout#redeem'
end

app/views/spree/admin/users/_store_credit_balance_sidebar.html.erb
<tr>
  <td><%= Spree.t('admin.user.store_credits') %>:</td>
  <td><%= Spree::Money.new(@user.total_available_store_credit).to_html %></td>
</tr>

app/views/spree/admin/users/_store_credits_sidebar.html.erb
<li<%== ' class="active"' if current == :store_credits %>>
  <%= link_to_with_icon 'money', Spree.t(:"admin.user.store_credit"), admin_user_store_credits_path(@user) %>
</li>
<li<%== ' class="active"' if current == :gift_cards %>>
  <%= link_to_with_icon 'gift', Spree.t(:"admin.gift_cards.redeem_gift_card"), lookup_admin_user_gift_cards_path(@user) %>
</li>

app/views/spree/admin/users/_sub_menu.html.erb
<% if request.fullpath.match(/^\/admin\/users/) %>
  <% content_for :sub_menu do %>
        <ul id="sub_nav" class="inline-menu">
          <%= tab :users %>
          <% if can?(:display, Spree::VirtualGiftCard) %>
              <%= tab :gift_cards, :match_path => '/users/gift_cards' %>
          <% end %>
        </ul>
  <% end %>
<% end %>