config/routes.rb
Spree::Core::Engine.routes.draw do
  namespace :admin do
    resources :store_credit_categories
    resources :users, only: [] do
      resources :store_credits

      resources :gift_cards, only: [] do
        collection do
          get :lookup
          post :redeem
        end
      end

      collection do
        resources :gift_cards, only: [:index, :show]
      end
    end
    resources :orders, only: [] do
      resources :gift_cards, only: [:edit, :update] do
        member do
          put :send_email
          put :deactivate
        end
      end
    end
  end

  namespace :api, defaults: { format: 'json' } do
    resources :store_credit_events, only: [] do
      collection do
        get :mine
      end
    end

    resources :gift_cards, only: [] do
      collection do
        post :redeem
      end
    end
  end

  post '/checkout/redeem', to: 'checkout#redeem'
end

app/models/spree/order/store_credit.rb
# NOTE: Remove for 3-1-stable

module Spree
  class Order < Spree::Base
    module StoreCredit
      def add_store_credit_payments

        payments.store_credits.where(state: 'checkout').map(&:invalidate!)

        authorized_total = payments.pending.sum(:amount)
        remaining_total = outstanding_balance - authorized_total

        if user && user.store_credits.any?
          payment_method = Spree::PaymentMethod.find_by_type('Spree::PaymentMethod::StoreCredit')
          raise "Store credit payment method could not be found" unless payment_method

          user.store_credits.order_by_priority.each do |credit|
            break if remaining_total.zero?
            next if credit.amount_remaining.zero?

            amount_to_take = store_credit_amount(credit, remaining_total)
            create_store_credit_payment(payment_method, credit, amount_to_take)
            remaining_total -= amount_to_take
          end
        end

        other_payments = payments.checkout.not_store_credits

        if remaining_total.zero?
          other_payments.each(&:invalidate!)
        elsif other_payments.size == 1
          other_payments.first.update_attributes!(amount: remaining_total)
        end

        payments.reset

        if payments.where(state: %w(checkout pending)).sum(:amount) != total
          errors.add(:base, Spree.t("store_credit.errors.unable_to_fund")) and return false
        end

      end

      def covered_by_store_credit?
        return false unless user
        user.total_available_store_credit >= total
      end

      alias_method :covered_by_store_credit, :covered_by_store_credit?

      def total_available_store_credit
        return 0.0 unless user
        user.total_available_store_credit
      end

      def could_use_store_credit?
        total_available_store_credit > 0
      end

      def order_total_after_store_credit
        total - total_applicable_store_credit
      end

      def total_applicable_store_credit
        if payment? || confirm? || complete?
          total_applied_store_credit
        else
          [total, (user.try(:total_available_store_credit) || 0.0)].min
        end
      end

      def total_applied_store_credit
        payments.store_credits.valid.sum(:amount)
      end

      def using_store_credit?
        total_applied_store_credit > 0
      end

      def display_total_applicable_store_credit
        Spree::Money.new(-total_applicable_store_credit, currency: currency)
      end

      def display_total_applied_store_credit
        Spree::Money.new(-total_applied_store_credit, currency: currency)
      end

      def display_order_total_after_store_credit
        Spree::Money.new(order_total_after_store_credit, currency: currency)
      end

      def display_total_available_store_credit
        Spree::Money.new(total_available_store_credit, currency: currency)
      end

      def display_store_credit_remaining_after_capture
        Spree::Money.new(total_available_store_credit - total_applicable_store_credit, currency: currency)
      end

      private

      def create_store_credit_payment(payment_method, credit, amount)
        payments.create!(
          source: credit,
          payment_method: payment_method,
          amount: amount,
          state: 'checkout',
          response_code: credit.generate_authorization_code
        )
      end

      def store_credit_amount(credit, total)
        [credit.amount_remaining, total].min
      end
    end
  end
end

app/views/spree/admin/orders/_cart_gift_card_details.html.erb
<% item.gift_cards.each do |gift_card| %>
    <%= render partial: "gift_card_details", locals: { gift_card: gift_card } %>
<% end %>

app/views/spree/admin/orders/_confirmation_gift_card_details.html.erb
<fieldset class="no-border-bottom">
  <legend align="center" data-hook="gift-card">
    <%= Spree.t(:gift_cards_details) %>
  </legend>
</fieldset>

<table>
  <colgroup>
    <col style="width: 15%;" />
    <col style="width: 15%;" />
    <col style="width: 15%;" />
    <col style="width: 30%;" />
    <col style="width: 10%;" />
    <col style="width: 15%;" />
  </colgroup>

  <thead>
  <th><%= Spree.t(:recipient_email) %></th>
  <th><%= Spree.t(:recipient_name) %></th>
  <th><%= Spree.t(:purchaser_name) %></th>
  <th><%= Spree.t(:gift_message) %></th>
  <th><%= Spree.t(:send_email_at) %></th>
  </thead>


  <tbody>
  <% @order.line_items.flat_map(&:gift_cards).each do |gift_card| %>
      <tr>
        <td>
          <%= gift_card.recipient_email || "n/a" %>
        </td>
        <td>
          <%= gift_card.recipient_name || "n/a" %>
        </td>
        <td>
          <%= gift_card.purchaser_name || "n/a" %>
        </td>
        <td>
          <%= gift_card.gift_message || "n/a" %>
        </td>
        <td>
          <%= gift_card.formatted_send_email_at || "Immediately" %>
        </td>
        <td class="actions">
          <%= link_to '', edit_admin_order_gift_card_path(@order, gift_card), :class => 'fa fa-edit no-text with-tip', :title => Spree.t('actions.edit') %>
        </td>
      </tr>
  <% end %>
  </tbody>
</table>

app/views/spree/admin/orders/_gift_card_details.html.erb
<br><strong><%= Spree.t('admin.gift_cards.redemption_code') %>:</strong> <%= gift_card.redemption_code %>
<br><%= link_to '(Edit Details)', edit_admin_order_gift_card_path(@order, gift_card), class: 'edit-gift-card-details' %>

app/views/spree/admin/orders/_gift_card_redemption_codes.html.erb
<% item.line_item.gift_cards.each do |gift_card| %>
  <br><strong><%= Spree.t('admin.gift_cards.redemption_code') %>:</strong> <%= gift_card.redemption_code %>
<% end %>

app/views/spree/admin/orders/_shipments_gift_card_details.html.erb
<% item.line_item.gift_cards.each do |gift_card| %>
    <%= render partial: "gift_card_details", locals: { gift_card: gift_card } %>
<% end %>